on:
 push: 
  branches:
   - master

jobs: 
  build:
    name: Push to Docker hub
    runs-on: ubuntu-latest
    steps: 
     - name: Check out repository
       uses: actions/checkout@v2 
     - name: Build docker
       run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/workshop .|
         docker push ${{ secrets.DOCKER_USERNAME }}/workshop
    

        