on:
 push: 
  branches:
   - master

jobs: 
  build:
    name: Push to Docker hub
    runs-on: ubuntu-latest
    steps: 
     - name: Check out repository
       uses: actions/checkout@v2 
     - uses: actions/docker/login@master
       with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
     - name: Build docker
       run: |
         docker build -t bobverheij/workshop |
         docker push bobverheij/workshop
    

        